version: '3.10'

services:
  # Django Web Application
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=freshconcept_ordering.settings
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - db
      - redis
    networks:
      - freshconcept-network

  # PostgreSQL Database
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - freshconcept-network

  # Redis Cache
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    networks:
      - freshconcept-network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  freshconcept-network:
    driver: bridge
